markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: P.Kerim  Friedman
url: "http://kerim.oxus.net/"
description: P. Kerim Friedman's Homepage.
twitter: kerim
facebook: kerimfriedman