# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Setup
title:            P. Kerim Friedman 傅可恩
tagline:          'P. Kerim Friedman 傅可恩'
description:      '<br/><a href="https://twitter.com/@kerim" target="_blank"><i class="fa fa-twitter"></i></a>&nbsp;&nbsp;&nbsp;<a href="https://facebook.com/kerimfriedman" target="_blank"><i class="fa fa-facebook"></i></a>&nbsp;&nbsp;&nbsp;<a href="https://plus.google.com/+KerimFriedman/about" target="_blank"><i class="fa fa-google-plus"></i></a>&nbsp;&nbsp;&nbsp;<a href="https://www.flickr.com/photos/kerim/" target="_blank" target="_blank"><i class="fa fa-flickr"></i></a>'
url:              http://kerim.github.io/
baseurl:          /

author:
  name:           'P. Kerim Friedman'
  url:            https://twitter.com/kerim

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
