remote_theme: kerim/academic

# General settings
title: P. Kerim Friedman 傅可恩
description: Kerim is a Taiwan-based anthropologist.
baseurl: ""
url: "https://kerim.oxus.net"

# Author
author: P. Kerim Friedman 傅可恩
email: fulaoshi@gms.ndhu.edu.tw
github_username: kerim
twitter_username: kerim
facebook_username: kerim.friedman

# Nav menu


# Favicon
favicon:
  safari: 5bbad5
  theme: ffffff

